stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

image: python:slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

black:
  stage: test
  script:
    - pip install black
    - echo "Performing Black formatting"
    - black $CI_PROJECT_DIR

pylint:
  stage: test
  script:
    - pip install pylint
    - echo "Performing lint checks"
    - pylint $CI_PROJECT_NAME --disable=E0401

deploy:
  stage: deploy
  variables:
    DEPLOY_CURL_COMMAND_BODY: "'{\"signal\":\"restart\"}'"
    DEPLOY_CURL_COMMAND: 'curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Authorization: Bearer $API_KEY" --data $DEPLOY_CURL_COMMAND_BODY https://control.sparkedhost.us/api/client/servers/85ca44fe/power'
  script:
    - apt-get update -qy
    - apt-get install -y lftp curl
    - exec $shell
    - echo "Starting deployment to server"
    - echo "Starting FTP upload"
    - lftp -e "debug; set sftp:auto-confirm yes; set ssl:verify-certificate false; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -X .* -X .*/ -X venv/ -X resources/ --reverse --verbose --delete; bye"
    - echo "sending CURL command to server to reboot"
    - eval "$DEPLOY_CURL_COMMAND"
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "main") 