[tool.pyright]
typeCheckingMode = "strict"
pythonVersion = "3.11" # replace with your py version
reportUnusedImport = "error"
reportUnnecessaryTypeIgnoreComment = "error"
reportIncompatibleMethodOverride = "none"
reportPrivateUsage = "none"
exclude = [
    "**/__pycache__",
    '.github'
]